version: '3.4'
services:
  client:
    build:
      context: .
      dockerfile: infra/node/Dockerfile
    container_name: client
    network_mode: "service:server"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - APP_ENV=development
    working_dir: /var/www/app/client
    volumes:
      - ./app/client:/var/www/app/client
    command: sh -c "yarn install && yarn start"
      
  server:
    build:
      context: .
      dockerfile: infra/go/Dockerfile
    container_name: server
    working_dir: /var/www/app/server
    volumes: 
      - ./app/server:/var/www/app/server
    entrypoint: "air"
    ports:
      - 3000:3000
      - 8080:8080
